
import = ["~/.cache/wal/colors-alacritty.toml"]

[shell]
program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 15.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 10
y = 10

#[window.dimensions]
#columns = 90
#lines = 25

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

