
import = ["~/.cache/wal/colors-alacritty.toml"]

[shell]
program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 16.5

[font.normal]
family = "Hack Nerd Font Mono"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 10
y = 10

#[window.dimensions]
#columns = 90
#lines = 25

